apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: codercom/code-server
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /home/coder/
          name: contents
        resources:
          limits:
            memory: "1024Mi"
          requests:
            memory: "512Mi"
        env:
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-secret
              key: password
      volumes:
      - name: contents
        persistentVolumeClaim:
          claimName: code-server-pvc
