apiVersion: v1
kind: Service
metadata:
  name: code-server-service
spec:
  type: NodePort
  selector:
    app: code-server
  ports:
    - name: "http-port"
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
